name: Python Package
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11]

    steps:
      - uses: actions/checkout@v3

      - name: Clone simulstream
        run: git clone https://github.com/hlt-mt/simulstream.git

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        working-directory: simulstream
        run: |
          pip install -e .[canary,eval]

      - name: Test with pytest
        run: |
          pip install pytest
          pytest tests/ -v